
variables:
  wget: "wget --quiet --tries=0"
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  TERM: dumb  # to stop verbose build output

.apt-template: &apt-template
- export LC_ALL=C.UTF-8
- export DEBIAN_FRONTEND=noninteractive
- echo Etc/UTC > /etc/timezone
- echo 'quiet "1";'
       'APT::Install-Recommends "0";'
       'APT::Install-Suggests "0";'
       'APT::Acquire::Retries "20";'
       'APT::Get::Assume-Yes "true";'
       'Dpkg::Use-Pty "0";'
      > /etc/apt/apt.conf.d/99gitlab
- echo "deb http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list
- apt-get update
- apt-get dist-upgrade
- apt-get install
      build-essential
      ca-certificates
      cmake
      git
      ninja-build
      openjdk-8-jdk-headless

.artifacts-template: &artifacts-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - build/
      - packages/*.*
      - "*/build/reports/"
    when:
      always
    expire_in: 1 week

# based on https://github.com/google/conscrypt/blob/master/.travis.yml
build and test:
  image: debian:buster-backports
  <<: *artifacts-template
  script:
    - *apt-template

    - export EXITVALUE=0
    - function set_error() {
          export EXITVALUE=1;
          printf "\x1b[31mERROR `history|tail -2|head -1|cut -b 6-500`\x1b[0m\n";
      }

    - apt-get install python3-argcomplete python3-requests
    - export ANDROID_SDK_HOME=/opt/android-sdk
    - export ANDROID_HOME=/opt/android-sdk
    - git clone --depth=1 https://gitlab.com/eighthave/sdkmanager.git
    - ndkVersion=$(sed -En 's,.*[nN]dkVersion\s*=?\s*.([1-9][0-9]\.[0-9]\.[0-9]{7}).*,\1,p' android/build.gradle)
    - ./sdkmanager/sdkmanager.py "tools;26.1.1" "ndk;$ndkVersion"
    - export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndks/$ndkVersion

    - apt-get install -t buster-backports golang-go  # needs >=1.13
    - export BORINGSSL_HOME=$PWD/boringssl
    - mkdir $BORINGSSL_HOME
    - git clone --depth 1 https://boringssl.googlesource.com/boringssl $BORINGSSL_HOME
    - mkdir $BORINGSSL_HOME/build64 && pushd $BORINGSSL_HOME/build64
    - cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release -DCMAKE_ASM_FLAGS=-Wa,--noexecstack
          -GNinja ..
    - ninja
    - popd

    - yes | ./sdkmanager/sdkmanager.py --licenses || true
    - ./sdkmanager/sdkmanager.py tools || set_error

    - ./gradlew build -PcheckErrorQueue || set_error
    - ./gradlew check -PcheckErrorQueue || set_error

    - ./gradlew :conscrypt-android:build || set_error
    - ./gradlew :conscrypt-android-platform:build || set_error
    - exit $EXITVALUE
